# Generated by Django 5.2.13 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_deleted_at_patient_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeuticevolution',
            name='released_to_family',
            field=models.BooleanField(default=False, verbose_name='Liberado para família'),
        ),
    ]
