# Generated by Django 5.2.13 on 2026-05-13 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_therapeuticevolution_released_to_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeuticevolution',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_evolutions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Criado por',
            ),
        ),
    ]
