# Generated by Django 5.2.13 on 2026-06-15 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_tenant_customuser_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='therapist',
            field=models.ForeignKey(
                db_constraint=False,
                limit_choices_to={'role': 'therapist'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Terapeuta',
            ),
        ),
        migrations.AlterField(
            model_name='therapeuticevolution',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_evolutions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Criado por',
            ),
        ),
    ]
