# Generated by Django 5.2.13 on 2026-06-15 11:59

import django.contrib.auth.models
from django.db import migrations

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_session_therapist_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.TenantScopedManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
